#!/usr/bin/env python3
"""
Email Spam Word Checker — local clone of Mailmeteor's spam checker.

Runs 772 regex patterns (5 categories) against email copy and flags
spam trigger words. Scoring algorithm matches Mailmeteor exactly.

Source: https://mailmeteor.com/assets/js/spam-checker.js (2025-04-21)

Usage:
    # Check a single email from stdin
    echo "Click here for a free offer!" | python spam_checker.py

    # Check a file
    python spam_checker.py --file email.txt

    # Check inline text
    python spam_checker.py --text "Act now, limited time only!"

    # JSON output (for programmatic use)
    python spam_checker.py --file email.txt --json

    # Check all emails in a directory
    python spam_checker.py --dir campaigns/

    # Quiet mode — only show flagged words
    python spam_checker.py --file email.txt --quiet
"""

import argparse
import json
import re
import sys
from pathlib import Path

# ─── Spam word database ─────────────────────────────────────────────
# 772 patterns across 5 categories, extracted from Mailmeteor's JS.
# Each entry: (compiled_regex, keyword_label, category)

SPAM_PATTERNS: list[tuple[re.Pattern, str, str]] = []

def _p(pattern: str, keyword: str, category: str):
    """Register a spam pattern."""
    SPAM_PATTERNS.append((re.compile(pattern, re.IGNORECASE), keyword, category))

# ── Urgency (91 patterns) ───────────────────────────────────────────
_p(r'\baccess\b', "Access", "urgency")
_p(r'\baccess now\b', "Access now", "urgency")
_p(r'\bact\b', "Act", "urgency")
_p(r'\bact immediately\b', "Act immediately", "urgency")
_p(r'\bact now\b', "Act now", "urgency")
_p(r'\bact now!\b', "Act now!", "urgency")
_p(r'\baction\b', "Action", "urgency")
_p(r'\baction required\b', "Action required", "urgency")
_p(r'\bapply here\b', "Apply here", "urgency")
_p(r'\bapply now\b', "Apply now", "urgency")
_p(r'\bapply now!\b', "Apply now!", "urgency")
_p(r'\bapply online\b', "Apply online", "urgency")
_p(r'\basap\b', "ASAP", "urgency")
_p(r'\bbecome a member\b', "Become a member", "urgency")
_p(r"\bbefore it's too late\b", "Before it's too late", "urgency")
_p(r'\bbeing a member\b', "Being a member", "urgency")
_p(r'\bbuy\b', "Buy", "urgency")
_p(r'\bbuy direct\b', "Buy direct", "urgency")
_p(r'\bbuy now\b', "Buy now", "urgency")
_p(r'\bbuy today\b', "Buy today", "urgency")
_p(r'\bcall\b', "Call", "urgency")
_p(r'\bcall free\b', "Call free", "urgency")
_p(r'\bcall (free|now)\b', "Call free/now", "urgency")
_p(r'\bcall me\b', "Call me", "urgency")
_p(r'\bcall now\b', "Call now", "urgency")
_p(r'\bcall now!\b', "Call now!", "urgency")
_p(r'\bcan we have a minute of your time\?\b', "Can we have a minute of your time?", "urgency")
_p(r'\bcancel now\b', "Cancel now", "urgency")
_p(r'\bcancellation required\b', "Cancellation required", "urgency")
_p(r'\bclaim now\b', "Claim now", "urgency")
_p(r'\bclick\b', "Click", "urgency")
_p(r'\bclick below\b', "Click below", "urgency")
_p(r'\bclick here\b', "Click here", "urgency")
_p(r'\bclick me to download\b', "Click me to download", "urgency")
_p(r'\bclick now\b', "Click now", "urgency")
_p(r'\bclick this link\b', "Click this link", "urgency")
_p(r'\bclick to get\b', "Click to get", "urgency")
_p(r'\bclick to remove\b', "Click to remove", "urgency")
_p(r'\bcontact us immediately\b', "Contact us immediately", "urgency")
_p(r'\bdeal ending soon\b', "Deal ending soon", "urgency")
_p(r'\bdo it now\b', "Do it now", "urgency")
_p(r'\bdo it today\b', "Do it today", "urgency")
_p(r"\bdon't delete\b", "Don't delete", "urgency")
_p(r"\bdon't hesitate\b", "Don't hesitate", "urgency")
_p(r"\bdon't waste time\b", "Don't waste time", "urgency")
_p(r'\bexclusive deal\b', "Exclusive deal", "urgency")
_p(r'\bexpire\b', "Expire", "urgency")
_p(r'\bexpires today\b', "Expires today", "urgency")
_p(r'\bfinal call\b', "Final call", "urgency")
_p(r'\bfor instant access\b', "For instant access", "urgency")
_p(r'\bfor only\b', "For Only", "urgency")
_p(r'\bfor you\b', "For you", "urgency")
_p(r'\bfriday before [holiday]\b', "Friday before [holiday]", "urgency")
_p(r'\bget it away\b', "Get it away", "urgency")
_p(r'\bget it now\b', "Get it now", "urgency")
_p(r'\bget now\b', "Get now", "urgency")
_p(r'\bget paid\b', "Get paid", "urgency")
_p(r'\bget started\b', "Get started", "urgency")
_p(r'\bget started now\b', "Get started now", "urgency")
_p(r'\bgreat offer\b', "Great offer", "urgency")
_p(r'\bhurry up\b', "Hurry up", "urgency")
_p(r'\bimmediately\b', "Immediately", "urgency")
_p(r'\binfo you requested\b', "Info you requested", "urgency")
_p(r'\binformation you requested\b', "Information you requested", "urgency")
_p(r'\binstant\b', "Instant", "urgency")
_p(r'\blimited time\b', "Limited time", "urgency")
_p(r'\bnew customers only\b', "New customers only", "urgency")
_p(r'\bnow\b', "Now", "urgency")
_p(r'\bnow only\b', "Now only", "urgency")
_p(r'\boffer expires\b', "Offer expires", "urgency")
_p(r'\bonce in lifetime\b', "Once in lifetime", "urgency")
_p(r'\bonly\b', "Only", "urgency")
_p(r'\border now\b', "Order now", "urgency")
_p(r'\border today\b', "Order today", "urgency")
_p(r'\bplease read\b', "Please read", "urgency")
_p(r'\bpurchase now\b', "Purchase now", "urgency")
_p(r'\bsign up free\b', "Sign up free", "urgency")
_p(r'\bsign up free today\b', "Sign up free today", "urgency")
_p(r'\bsupplies are limited\b', "Supplies are limited", "urgency")
_p(r'\btake action\b', "Take action", "urgency")
_p(r'\btake action now\b', "Take action now", "urgency")
_p(r"\bthis won't last\b", "This won't last", "urgency")
_p(r'\btime limited\b', "Time limited", "urgency")
_p(r'\btoday\b', "Today", "urgency")
_p(r'\btop urgent\b', "Top urgent", "urgency")
_p(r'\btrial\b', "Trial", "urgency")
_p(r'\burgent\b', "Urgent", "urgency")
_p(r'\bwhat are you waiting for\?\b', "What are you waiting for?", "urgency")
_p(r'\bwhile supplies last\b', "While supplies last", "urgency")
_p(r'\byou are a winner\b', "You are a winner", "urgency")

# ── Shady (399 patterns) ────────────────────────────────────────────
_p(r'\b0 down\b', "0 down", "shady")
_p(r'\ball\b', "All", "shady")
_p(r'\ball natural\b', "All natural", "shady")
_p(r'\ball (natural|new)\b', "All natural/new", "shady")
_p(r'\ball new\b', "All new", "shady")
_p(r'\ball-natural\b', "All-natural", "shady")
_p(r'\ball-new\b', "All-new", "shady")
_p(r'\ballowance\b', "Allowance", "shady")
_p(r'\bas seen on\b', "As seen on", "shady")
_p(r'\bas seen on oprah\b', "As seen on Oprah", "shady")
_p(r'\bat no cost\b', "At no cost", "shady")
_p(r'\bauto email removal\b', "Auto email removal", "shady")
_p(r'\bavoice bankruptcy\b', "Avoice bankruptcy", "shady")
_p(r'\bavoid\b', "Avoid", "shady")
_p(r'\bbeneficial offer\b', "Beneficial offer", "shady")
_p(r'\bbeneficiary\b', "Beneficiary", "shady")
_p(r'\bbill 1618\b', "Bill 1618", "shady")
_p(r'\bbrand new pager\b', "Brand new pager", "shady")
_p(r'\bbulk email\b', "Bulk email", "shady")
_p(r'\bbuying judgements\b', "Buying judgements", "shady")
_p(r'\bbuying judgments\b', "Buying judgments", "shady")
_p(r'\bcable converter\b', "Cable converter", "shady")
_p(r'\bcalling creditors\b', "Calling creditors", "shady")
_p(r'\bcan you help us\?\b', "Can you help us?", "shady")
_p(r'\bcancel at any time\b', "Cancel at any time", "shady")
_p(r'\bcannot be combined\b', "Cannot be combined", "shady")
_p(r'\bcelebrity\b', "Celebrity", "shady")
_p(r'\bcell phone cancer scam\b', "Cell phone cancer scam", "shady")
_p(r'\bcertified\b', "Certified", "shady")
_p(r'\bchance\b', "Chance", "shady")
_p(r'\bcheap\b', "Cheap", "shady")
_p(r'\bcheap meds\b', "Cheap meds", "shady")
_p(r'\bcialis\b', "Cialis", "shady")
_p(r'\bclaims\b', "Claims", "shady")
_p(r'\bclaims not to be selling anything\b', "Claims not to be selling anything", "shady")
_p(r'\bclaims to be in accordance with some spam law\b', "Claims to be in accordance with some spam law", "shady")
_p(r'\bclaims to be legal\b', "Claims to be legal", "shady")
_p(r'\bclearance\b', "Clearance", "shady")
_p(r'\bcollect\b', "Collect", "shady")
_p(r'\bcollect child support\b', "Collect child support", "shady")
_p(r'\bcompare\b', "Compare", "shady")
_p(r'\bcompare now\b', "Compare now", "shady")
_p(r'\bcompare online\b', "Compare online", "shady")
_p(r'\bcompare rates\b', "Compare rates", "shady")
_p(r'\bcompete for your business\b', "Compete for your business", "shady")
_p(r'\bconfidentiality\b', "Confidentiality", "shady")
_p(r'\bcongratulations\b', "Congratulations", "shady")
_p(r'\bconsolidate debt and credit\b', "Consolidate debt and credit", "shady")
_p(r'\bconsolidate your debt\b', "Consolidate your debt", "shady")
_p(r'\bcopy accurately\b', "Copy accurately", "shady")
_p(r'\bcopy dvds\b', "Copy DVDs", "shady")
_p(r'\bcovid\b', "COVID", "shady")
_p(r'\bcures\b', "Cures", "shady")
_p(r'\bcures baldness\b', "Cures baldness", "shady")
_p(r'\bdiagnostic\b', "Diagnostic", "shady")
_p(r'\bdiagnostics\b', "DIAGNOSTICS", "shady")
_p(r'\bdiet\b', "Diet", "shady")
_p(r'\bdig up dirt on friends\b', "Dig up dirt on friends", "shady")
_p(r'\bdirect email\b', "Direct email", "shady")
_p(r'\bdirect marketing\b', "Direct marketing", "shady")
_p(r'\beliminate debt\b', "Eliminate debt", "shady")
_p(r'\bexplode your business\b', "Explode your business", "shady")
_p(r'\bfast viagra delivery\b', "Fast viagra delivery", "shady")
_p(r'\bfinance\b', "Finance", "shady")
_p(r'\bfinancial\b', "Financial", "shady")
_p(r'\bfinancial advice\b', "Financial advice", "shady")
_p(r'\bfinancial independence\b', "Financial independence", "shady")
_p(r'\bfinancially independent\b', "Financially independent", "shady")
_p(r'\bfor new customers only\b', "For new customers only", "shady")
_p(r'\bforeclosure\b', "Foreclosure", "shady")
_p(r'\bfree\b', "Free", "shady")
_p(r'\bfree (access|money|gift)\b', "Free access/money/gift", "shady")
_p(r'\bfree bonus\b', "Free bonus", "shady")
_p(r'\bfree cell phone\b', "Free cell phone", "shady")
_p(r'\bfree dvd\b', "Free DVD", "shady")
_p(r'\bfree grant money\b', "Free grant money", "shady")
_p(r'\bfree information\b', "Free information", "shady")
_p(r'\bfree installation\b', "Free installation", "shady")
_p(r'\bfree instant\b', "Free Instant", "shady")
_p(r'\bfree iphone\b', "Free iPhone", "shady")
_p(r'\bfree laptop\b', "Free laptop", "shady")
_p(r'\bfree leads\b', "Free leads", "shady")
_p(r'\bfree macbook\b', "Free Macbook", "shady")
_p(r'\bfree offer\b', "Free offer", "shady")
_p(r'\bfree priority mail\b', "Free priority mail", "shady")
_p(r'\bfree sample\b', "Free sample", "shady")
_p(r'\bfree website\b', "Free website", "shady")
_p(r'\bfree!\b', "Free!", "shady")
_p(r'\bget\b', "Get", "shady")
_p(r'\bgift card\b', "Gift card", "shady")
_p(r'\bgift certificate\b', "Gift certificate", "shady")
_p(r'\bgift included\b', "Gift included", "shady")
_p(r'\bgive it away\b', "Give it away", "shady")
_p(r'\bgiving away\b', "Giving away", "shady")
_p(r'\bgiving it away\b', "Giving it away", "shady")
_p(r'\bgold\b', "Gold", "shady")
_p(r'\bgreat\b', "Great", "shady")
_p(r'\bgreat deal\b', "Great deal", "shady")
_p(r'\bgreetings of the day\b', "Greetings of the day", "shady")
_p(r'\bgrowth hormone\b', "Growth hormone", "shady")
_p(r'\bguarantee\b', "Guarantee", "shady")
_p(r'\bguaranteed deposit\b', "Guaranteed deposit", "shady")
_p(r'\bguaranteed income\b', "Guaranteed income", "shady")
_p(r'\bguaranteed payment\b', "Guaranteed payment", "shady")
_p(r'\bhave you been turned down\?\b', "Have you been turned down?", "shady")
_p(r'\bhello (with no name included)\b', "Hello (with no name included)", "shady")
_p(r'\bhidden charges\b', "Hidden charges", "shady")
_p(r'\bhidden costs\b', "Hidden costs", "shady")
_p(r'\bhidden fees\b', "Hidden fees", "shady")
_p(r'\bhigh score\b', "High score", "shady")
_p(r'\bhome based business\b', "Home based business", "shady")
_p(r'\bhome mortgage\b', "Home mortgage", "shady")
_p(r'\bhuman\b', "Human", "shady")
_p(r'\bhuman growth hormone\b', "Human growth hormone", "shady")
_p(r'\bif only it were that easy\b', "If only it were that easy", "shady")
_p(r'\bimportant information\b', "Important information", "shady")
_p(r'\bimportant notification\b', "Important notification", "shady")
_p(r'\binstant weight loss\b', "Instant weight loss", "shady")
_p(r'\binsurance lose weight\b', "Insurance Lose weight", "shady")
_p(r'\binternet marketing\b', "Internet marketing", "shady")
_p(r'\binvestment decision\b', "Investment decision", "shady")
_p(r'\binvoice\b', "Invoice", "shady")
_p(r"\bit's effective\b", "It's effective", "shady")
_p(r'\bjob alert\b', "Job alert", "shady")
_p(r'\bjunk\b', "Junk", "shady")
_p(r'\blambo\b', "Lambo", "shady")
_p(r'\blaser printer\b', "Laser printer", "shady")
_p(r'\blast day\b', "Last Day", "shady")
_p(r'\blegal\b', "Legal", "shady")
_p(r'\blegal notice\b', "Legal notice", "shady")
_p(r'\blife\b', "Life", "shady")
_p(r'\blife insurance\b', "Life insurance", "shady")
_p(r'\blifetime access\b', "Lifetime access", "shady")
_p(r'\blifetime deal\b', "Lifetime deal", "shady")
_p(r'\blimited\b', "Limited", "shady")
_p(r'\blimited amount\b', "Limited amount", "shady")
_p(r'\blimited number\b', "Limited number", "shady")
_p(r'\blimited offer\b', "Limited offer", "shady")
_p(r'\blimited supply\b', "Limited supply", "shady")
_p(r'\blimited time offer\b', "Limited time offer", "shady")
_p(r'\blimited time only\b', "Limited time only", "shady")
_p(r'\bloan\b', "Loan", "shady")
_p(r'\blong distance phone number\b', "Long distance phone number", "shady")
_p(r'\blong distance phone offer\b', "Long distance phone offer", "shady")
_p(r'\blose weight\b', "Lose weight", "shady")
_p(r'\blose weight fast\b', "Lose weight fast", "shady")
_p(r'\blose weight spam\b', "Lose weight spam", "shady")
_p(r'\blottery\b', "Lottery", "shady")
_p(r'\blower interest rate\b', "Lower interest rate", "shady")
_p(r'\blower interest rates\b', "Lower interest rates", "shady")
_p(r'\blower monthly payment\b', "Lower monthly payment", "shady")
_p(r'\blower your mortgage rate\b', "Lower your mortgage rate", "shady")
_p(r'\blowest insurance rates\b', "Lowest insurance rates", "shady")
_p(r'\blowest interest rate\b', "Lowest interest rate", "shady")
_p(r'\blowest rate\b', "Lowest rate", "shady")
_p(r'\blowest rates\b', "Lowest rates", "shady")
_p(r'\bluxury\b', "Luxury", "shady")
_p(r'\bluxury car\b', "Luxury car", "shady")
_p(r'\bmail in order form\b', "Mail in order form", "shady")
_p(r'\bmain in order form\b', "Main in order form", "shady")
_p(r'\bmark this as not junk\b', "Mark this as not junk", "shady")
_p(r'\bmass email\b', "Mass email", "shady")
_p(r'\bmedical\b', "Medical", "shady")
_p(r'\bmedicine\b', "Medicine", "shady")
_p(r'\bmeet girls\b', "Meet girls", "shady")
_p(r'\bmeet me\b', "Meet me", "shady")
_p(r'\bmeet singles\b', "Meet singles", "shady")
_p(r'\bmeet women\b', "Meet women", "shady")
_p(r'\bmember\b', "Member", "shady")
_p(r'\bmember stuff\b', "Member stuff", "shady")
_p(r'\bmessage contains disclaimer\b', "Message contains disclaimer", "shady")
_p(r'\bmessage from\b', "Message from", "shady")
_p(r'\bmillionaire\b', "Millionaire", "shady")
_p(r'\bmillions\b', "Millions", "shady")
_p(r'\bmlm\b', "MLM", "shady")
_p(r'\bmulti-level marketing\b', "Multi-level marketing", "shady")
_p(r'\bname\b', "Name", "shady")
_p(r'\bnear you\b', "Near you", "shady")
_p(r'\bnever before\b', "Never before", "shady")
_p(r'\bnew\b', "New", "shady")
_p(r'\bnew domain extensions\b', "New domain extensions", "shady")
_p(r'\bnigerian\b', "Nigerian", "shady")
_p(r'\bno age restrictions\b', "No age restrictions", "shady")
_p(r'\bno catch\b', "No catch", "shady")
_p(r'\bno claim forms\b', "No claim forms", "shady")
_p(r'\bno cost\b', "No cost", "shady")
_p(r'\bno credit check\b', "No credit check", "shady")
_p(r'\bno credit experience\b', "No credit experience", "shady")
_p(r'\bno deposit required\b', "No deposit required", "shady")
_p(r'\bno disappointment\b', "No disappointment", "shady")
_p(r'\bno experience\b', "No experience", "shady")
_p(r'\bno fees\b', "No fees", "shady")
_p(r'\bno gimmick\b', "No gimmick", "shady")
_p(r'\bno hidden\b', "No hidden", "shady")
_p(r'\bno hidden costs\b', "No hidden costs", "shady")
_p(r'\bno hidden fees\b', "No hidden fees", "shady")
_p(r'\bno interest\b', "No interest", "shady")
_p(r'\bno interests\b', "No interests", "shady")
_p(r'\bno inventory\b', "No inventory", "shady")
_p(r'\bno investment\b', "No investment", "shady")
_p(r'\bno investment required\b', "No investment required", "shady")
_p(r'\bno medical exams\b', "No medical exams", "shady")
_p(r'\bno middleman\b', "No middleman", "shady")
_p(r'\bno obligation\b', "No obligation", "shady")
_p(r'\bno payment required\b', "No payment required", "shady")
_p(r'\bno purchase necessary\b', "No purchase necessary", "shady")
_p(r'\bno questions asked\b', "No questions asked", "shady")
_p(r'\bno selling\b', "No selling", "shady")
_p(r'\bno strings attached\b', "No strings attached", "shady")
_p(r'\bno-obligation\b', "No-obligation", "shady")
_p(r'\bnominated bank account\b', "Nominated bank account", "shady")
_p(r'\bnot intended\b', "Not intended", "shady")
_p(r'\bnot junk\b', "Not junk", "shady")
_p(r'\bnot scam\b', "Not scam", "shady")
_p(r'\bnot spam\b', "Not spam", "shady")
_p(r'\bnotspam\b', "Notspam", "shady")
_p(r'\bnumber 1\b', "Number 1", "shady")
_p(r'\bobligation\b', "Obligation", "shady")
_p(r'\boff\b', "Off", "shady")
_p(r'\boff everything\b', "Off everything", "shady")
_p(r'\boff shore\b', "Off shore", "shady")
_p(r'\boffer extended\b', "Offer extended", "shady")
_p(r'\boffers\b', "Offers", "shady")
_p(r'\boffshore\b', "Offshore", "shady")
_p(r'\bone hundred percent\b', "One hundred percent", "shady")
_p(r'\bone-time\b', "One-time", "shady")
_p(r'\bonline biz opportunity\b', "Online biz opportunity", "shady")
_p(r'\bonline degree\b', "Online degree", "shady")
_p(r'\bonline income\b', "Online income", "shady")
_p(r'\bonline job\b', "Online job", "shady")
_p(r'\bopen\b', "Open", "shady")
_p(r'\bopportunity\b', "Opportunity", "shady")
_p(r'\bopt-in\b', "Opt-in", "shady")
_p(r'\border\b', "Order", "shady")
_p(r'\border shipped by\b', "Order shipped by", "shady")
_p(r'\border status\b', "Order status", "shady")
_p(r'\borders shipped by\b', "Orders shipped by", "shady")
_p(r'\borders shipped by shopper\b', "Orders shipped by shopper", "shady")
_p(r'\boutstanding value\b', "Outstanding value", "shady")
_p(r'\boutstanding values\b', "Outstanding values", "shady")
_p(r'\bpassword\b', "Password", "shady")
_p(r'\bpasswords\b', "Passwords", "shady")
_p(r'\bpay your bills\b', "Pay your bills", "shady")
_p(r'\bper (day|week|year)\b', "Per day/per week/per year", "shady")
_p(r'\bper month\b', "Per month", "shady")
_p(r'\bperfect\b', "Perfect", "shady")
_p(r'\bperformance\b', "Performance", "shady")
_p(r'\bphone\b', "Phone", "shady")
_p(r'\bplease\b', "Please", "shady")
_p(r'\bplease open\b', "Please open", "shady")
_p(r'\bpresently\b', "Presently", "shady")
_p(r'\bprint form signature\b', "Print form signature", "shady")
_p(r'\bprint from signature\b', "Print from signature", "shady")
_p(r'\bprint out and fax\b', "Print out and fax", "shady")
_p(r'\bpriority mail\b', "Priority mail", "shady")
_p(r'\bprivately owned funds\b', "Privately owned funds", "shady")
_p(r'\bprizes\b', "Prizes", "shady")
_p(r'\bproblem with shipping\b', "Problem with shipping", "shady")
_p(r'\bproblem with your order\b', "Problem with your order", "shady")
_p(r'\bproduced and sent out\b', "Produced and sent out", "shady")
_p(r'\bprofit\b', "Profit", "shady")
_p(r'\bpromise you\b', "Promise you", "shady")
_p(r'\bpurchase\b', "Purchase", "shady")
_p(r'\bpure profits\b', "Pure Profits", "shady")
_p(r'\bquotes\b', "Quotes", "shady")
_p(r'\brate\b', "Rate", "shady")
_p(r'\breal thing\b', "Real thing", "shady")
_p(r'\brebate\b', "Rebate", "shady")
_p(r'\breduce debt\b', "Reduce debt", "shady")
_p(r'\brefinance home\b', "Refinance home", "shady")
_p(r'\brefinanced home\b', "Refinanced home", "shady")
_p(r'\brefund\b', "Refund", "shady")
_p(r'\bregarding\b', "Regarding", "shady")
_p(r'\bremoval instructions\b', "Removal instructions", "shady")
_p(r'\bremoves\b', "Removes", "shady")
_p(r'\bremoves wrinkles\b', "Removes wrinkles", "shady")
_p(r'\breplica watches\b', "Replica watches", "shady")
_p(r'\brequest\b', "Request", "shady")
_p(r'\brequest now\b', "Request now", "shady")
_p(r'\brequest today\b', "Request today", "shady")
_p(r'\brequires initial investment\b', "Requires initial investment", "shady")
_p(r'\brequires investment\b', "Requires investment", "shady")
_p(r'\breverses aging\b', "Reverses aging", "shady")
_p(r'\brisk free\b', "Risk free", "shady")
_p(r'\brolex\b', "Rolex", "shady")
_p(r'\bround the world\b', "Round the world", "shady")
_p(r'\bs 1618\b', "S 1618", "shady")
_p(r'\bsafeguard notice\b', "Safeguard notice", "shady")
_p(r'\bsale\b', "Sale", "shady")
_p(r'\bsales\b', "Sales", "shady")
_p(r'\bsave\b', "Save", "shady")
_p(r'\bsave big\b', "Save big", "shady")
_p(r'\bsave big month\b', "Save big month", "shady")
_p(r'\bsave money\b', "Save money", "shady")
_p(r'\bsave now\b', "Save now", "shady")
_p(r'\bscore with babes\b', "Score with babes", "shady")
_p(r'\bsearch engine optimisation\b', "Search engine optimisation", "shady")
_p(r'\bsection 301\b', "Section 301", "shady")
_p(r'\bsee for yourself\b', "See for yourself", "shady")
_p(r'\bseen on\b', "Seen on", "shady")
_p(r'\bserious\b', "Serious", "shady")
_p(r'\bserious case\b', "Serious case", "shady")
_p(r'\bserious offer\b', "Serious offer", "shady")
_p(r'\bserious only\b', "Serious only", "shady")
_p(r'\bsex\b', "Sex", "shady")
_p(r'\bshop now\b', "Shop now", "shady")
_p(r'\bshopper\b', "Shopper", "shady")
_p(r'\bshopping spree\b', "Shopping spree", "shady")
_p(r'\bsnoring\b', "Snoring", "shady")
_p(r'\bsocial security number\b', "Social security number", "shady")
_p(r'\bsoon\b', "Soon", "shady")
_p(r'\bspam\b', "Spam", "shady")
_p(r'\bspam free\b', "Spam free", "shady")
_p(r'\bspecial deal\b', "Special deal", "shady")
_p(r'\bspecial discount\b', "Special discount", "shady")
_p(r'\bspecial for you\b', "Special for you", "shady")
_p(r'\bspecial offer\b', "Special offer", "shady")
_p(r'\bstainless steel\b', "Stainless steel", "shady")
_p(r'\bstock alert\b', "Stock alert", "shady")
_p(r'\bstock disclaimer statement\b', "Stock disclaimer statement", "shady")
_p(r'\bstock pick\b', "Stock pick", "shady")
_p(r'\bstocks? (pick|alert)\b', "Stocks/stock pick/stock alert", "shady")
_p(r'\bstop calling me\b', "Stop calling me", "shady")
_p(r'\bstop emailing me\b', "Stop emailing me", "shady")
_p(r'\bstop further distribution\b', "Stop further distribution", "shady")
_p(r'\bstop snoring\b', "Stop snoring", "shady")
_p(r'\bstrong buy\b', "Strong buy", "shady")
_p(r'\bstuff on sale\b', "Stuff on sale", "shady")
_p(r'\bsubject to\b', "Subject to", "shady")
_p(r'\bsubject to cash\b', "Subject to cash", "shady")
_p(r'\bsubscribe\b', "Subscribe", "shady")
_p(r'\bsubscribe for free\b', "Subscribe for free", "shady")
_p(r'\bsubscribe now\b', "Subscribe now", "shady")
_p(r'\bsuper promo\b', "Super promo", "shady")
_p(r'\bsupplies\b', "Supplies", "shady")
_p(r'\btack action now\b', "Tack action now", "shady")
_p(r'\btalks about hidden charges\b', "Talks about hidden charges", "shady")
_p(r'\btalks about prizes\b', "Talks about prizes", "shady")
_p(r"\btells you it's an ad\b", "Tells you it's an ad", "shady")
_p(r'\bterms\b', "Terms", "shady")
_p(r'\bthe best rates\b', "The best rates", "shady")
_p(r'\bthe email asks for a credit card\b', "The email asks for a credit card", "shady")
_p(r'\bthe following form\b', "The following form", "shady")
_p(r"\bthey make a claim or claims that they're in accordance with spam law\b", "They make a claim or claims that they're in accordance with spam law", "shady")
_p(r'\bthey try to keep your money no refund\b', "They try to keep your money no refund", "shady")
_p(r"\bthey're just giving it away\b", "They're just giving it away", "shady")
_p(r"\bthis isn't junk\b", "This isn't junk", "shady")
_p(r"\bthis isn't spam\b", "This isn't spam", "shady")
_p(r"\bthis isn't a scam\b", "This isn't a scam", "shady")
_p(r'\btimeshare\b', "Timeshare", "shady")
_p(r'\btimeshare offers\b', "Timeshare offers", "shady")
_p(r'\btraffic\b', "Traffic", "shady")
_p(r'\btrial unlimited\b', "Trial unlimited", "shady")
_p(r'\bu.s. dollars\b', "U.S. dollars", "shady")
_p(r'\bundisclosed\b', "Undisclosed", "shady")
_p(r'\bundisclosed recipient\b', "Undisclosed recipient", "shady")
_p(r'\buniversity diplomas\b', "University diplomas", "shady")
_p(r'\bunsecured credit\b', "Unsecured credit", "shady")
_p(r'\bunsecured debt\b', "Unsecured debt", "shady")
_p(r'\bunsolicited\b', "Unsolicited", "shady")
_p(r'\bunsubscribe\b', "Unsubscribe", "shady")
_p(r'\burgent response\b', "Urgent response", "shady")
_p(r'\bUS Dollars|euros\b', "US Dollars / Euros", "shady")
_p(r'\bvacation\b', "Vacation", "shady")
_p(r'\bvacation offers\b', "Vacation offers", "shady")
_p(r'\bvalium\b', "Valium", "shady")
_p(r'\bviagra\b', "Viagra", "shady")
_p(r'\bvicodin\b', "Vicodin", "shady")
_p(r'\bvip\b', "VIP", "shady")
_p(r'\bvisit our website\b', "Visit our website", "shady")
_p(r'\bwants credit card\b', "Wants credit card", "shady")
_p(r'\bwarranty expired\b', "Warranty expired", "shady")
_p(r'\bwe hate spam\b', "We hate spam", "shady")
_p(r'\bwe honor all\b', "We honor all", "shady")
_p(r'\bwebsite visitors\b', "Website visitors", "shady")
_p(r'\bweekend getaway\b', "Weekend getaway", "shady")
_p(r'\bweight loss\b', "Weight loss", "shady")
_p(r"\bwhat's keeping you\?\b", "What's keeping you?", "shady")
_p(r'\bwhile available\b', "While available", "shady")
_p(r'\bwhile in stock\b', "While in stock", "shady")
_p(r'\bwhile stocks last\b', "While stocks last", "shady")
_p(r'\bwhile you sleep\b', "While you sleep", "shady")
_p(r'\bwho really wins\?\b', "Who really wins?", "shady")
_p(r'\bwin\b', "Win", "shady")
_p(r'\bwinner\b', "Winner", "shady")
_p(r'\bwinning\b', "Winning", "shady")
_p(r'\bwon\b', "Won", "shady")
_p(r'\bxanax\b', "Xanax", "shady")
_p(r'\bxxx\b', "XXX", "shady")
_p(r'\byou have been chosen\b', "You have been chosen", "shady")
_p(r'\byou have been selected\b', "You have been selected", "shady")
_p(r'\byour chance\b', "Your chance", "shady")
_p(r'\byour status\b', "Your status", "shady")
_p(r'\bzero chance\b', "Zero chance", "shady")
_p(r'\bzero percent\b', "Zero percent", "shady")
_p(r'\bzero risk\b', "Zero risk", "shady")

# ── Overpromise (103 patterns) ───────────────────────────────────────
_p(r'\b#1\b', "#1", "overpromise")
_p(r'[0-9]+%', "%", "overpromise")
_p(r'[0-9]+% free', "% free", "overpromise")
_p(r'\b[0-9]+% satisfied\b', "% Satisfied", "overpromise")
_p(r'\b[0-9]+%\b', "0%", "overpromise")
_p(r'\b[0-9]+% risk\b', "0% risk", "overpromise")
_p(r'\b100%\b', "100%", "overpromise")
_p(r'\b100% free\b', "100% free", "overpromise")
_p(r'\b100% more\b', "100% more", "overpromise")
_p(r'\b100% off\b', "100% off", "overpromise")
_p(r'\b100% satisfied\b', "100% satisfied", "overpromise")
_p(r'\b99\.90%\b', "99.90%", "overpromise")
_p(r'\b99%\b', "99%", "overpromise")
_p(r'\baccess for free\b', "Access for free", "overpromise")
_p(r'\badditional income\b', "Additional income", "overpromise")
_p(r'\bamazed\b', "Amazed", "overpromise")
_p(r'\bamazing\b', "Amazing", "overpromise")
_p(r'\bamazing offer\b', "Amazing offer", "overpromise")
_p(r'\bamazing stuff\b', "Amazing stuff", "overpromise")
_p(r'\bbe amazed\b', "Be amazed", "overpromise")
_p(r'\bbe surprised\b', "Be surprised", "overpromise")
_p(r'\bbe your own boss\b', "Be your own boss", "overpromise")
_p(r'\bbelieve me\b', "Believe me", "overpromise")
_p(r'\bbest bargain\b', "Best bargain", "overpromise")
_p(r'\bbest deal\b', "Best deal", "overpromise")
_p(r'\bbest offer\b', "Best offer", "overpromise")
_p(r'\bbest price\b', "Best price", "overpromise")
_p(r'\bbest rates\b', "Best rates", "overpromise")
_p(r'\bbig bucks\b', "Big bucks", "overpromise")
_p(r'\bbonus\b', "Bonus", "overpromise")
_p(r'\bboss\b', "Boss", "overpromise")
_p(r"\bcan't live without\b", "Can't live without", "overpromise")
_p(r'\bcancel\b', "Cancel", "overpromise")
_p(r'\bconsolidate debt\b', "Consolidate debt", "overpromise")
_p(r'\bdouble your cash\b', "Double your cash", "overpromise")
_p(r'\bdouble your income\b', "Double your income", "overpromise")
_p(r'\bdrastically reduced\b', "Drastically reduced", "overpromise")
_p(r'\bearn extra cash\b', "Earn extra cash", "overpromise")
_p(r'\bearn money\b', "Earn money", "overpromise")
_p(r'\beliminate bad credit\b', "Eliminate bad credit", "overpromise")
_p(r'\bexpect to earn\b', "Expect to earn", "overpromise")
_p(r'\bextra\b', "Extra", "overpromise")
_p(r'\bextra cash\b', "Extra cash", "overpromise")
_p(r'\bextra income\b', "Extra income", "overpromise")
_p(r'\bfantastic\b', "Fantastic", "overpromise")
_p(r'\bfantastic deal\b', "Fantastic deal", "overpromise")
_p(r'\bfantastic offer\b', "Fantastic offer", "overpromise")
_p(r'\bfast\b', "FAST", "overpromise")
_p(r'\bfast cash\b', "Fast cash", "overpromise")
_p(r'\bfinancial freedom\b', "Financial freedom", "overpromise")
_p(r'\bfree access\b', "Free access", "overpromise")
_p(r'\bfree consultation\b', "Free consultation", "overpromise")
_p(r'\bfree gift\b', "Free gift", "overpromise")
_p(r'\bfree hosting\b', "Free hosting", "overpromise")
_p(r'\bfree info\b', "Free info", "overpromise")
_p(r'\bfree investment\b', "Free investment", "overpromise")
_p(r'\bfree membership\b', "Free membership", "overpromise")
_p(r'\bfree money\b', "Free money", "overpromise")
_p(r'\bfree preview\b', "Free preview", "overpromise")
_p(r'\bfree quote\b', "Free quote", "overpromise")
_p(r'\bfree trial\b', "Free trial", "overpromise")
_p(r'\bfull refund\b', "Full refund", "overpromise")
_p(r'\bget out of debt\b', "Get out of debt", "overpromise")
_p(r'\bgiveaway\b', "Giveaway", "overpromise")
_p(r'\bguaranteed\b', "Guaranteed", "overpromise")
_p(r'\bincrease sales\b', "Increase sales", "overpromise")
_p(r'\bincrease traffic\b', "Increase traffic", "overpromise")
_p(r'\bincredible deal\b', "Incredible deal", "overpromise")
_p(r'\bjoin billions\b', "Join billions", "overpromise")
_p(r'\bjoin millions\b', "Join millions", "overpromise")
_p(r'\bjoin millions of americans\b', "Join millions of Americans", "overpromise")
_p(r'\bjoin thousands\b', "Join thousands", "overpromise")
_p(r'\blower rates\b', "Lower rates", "overpromise")
_p(r'\blowest price\b', "Lowest price", "overpromise")
_p(r'\bmake money\b', "Make money", "overpromise")
_p(r'\bmillion\b', "Million", "overpromise")
_p(r'\bmillion dollars\b', "Million dollars", "overpromise")
_p(r'\bmiracle\b', "Miracle", "overpromise")
_p(r'\bmoney back\b', "Money back", "overpromise")
_p(r'\bmonth trial offer\b', "Month trial offer", "overpromise")
_p(r'\bmore internet traffic\b', "More Internet Traffic", "overpromise")
_p(r'\bnumber one\b', "Number one", "overpromise")
_p(r'\bonce in a lifetime\b', "Once in a lifetime", "overpromise")
_p(r'\bone hundred percent guaranteed\b', "One hundred percent guaranteed", "overpromise")
_p(r'\bone time\b', "One time", "overpromise")
_p(r'\bpennies a day\b', "Pennies a day", "overpromise")
_p(r'\bpotential earnings\b', "Potential earnings", "overpromise")
_p(r'\bprize\b', "Prize", "overpromise")
_p(r'\bpromise\b', "Promise", "overpromise")
_p(r'\bpure profit\b', "Pure profit", "overpromise")
_p(r'\brisk-free\b', "Risk-free", "overpromise")
_p(r'\bsatisfaction guaranteed\b', "Satisfaction guaranteed", "overpromise")
_p(r'\bsave big money\b', "Save big money", "overpromise")
_p(r'\bsave up to\b', "Save up to", "overpromise")
_p(r'\bspecial promotion\b', "Special promotion", "overpromise")
_p(r'\bthe best\b', "The best", "overpromise")
_p(r'\bthousands\b', "Thousands", "overpromise")
_p(r'\bunbeatable offer\b', "Unbeatable offer", "overpromise")
_p(r'\bunbelievable\b', "Unbelievable", "overpromise")
_p(r'\bunlimited\b', "Unlimited", "overpromise")
_p(r'\bunlimited trial\b', "Unlimited trial", "overpromise")
_p(r'\bwonderful\b', "Wonderful", "overpromise")
_p(r'\byou will not believe your eyes\b', "You will not believe your eyes", "overpromise")

# ── Money (101 patterns) ────────────────────────────────────────────
_p(r'[\$\£\€\¥]+[0-9\.\,]+', "$$$", "money")
_p(r'[0-9\.\,]+[\$\£\€\¥]+', "€€€", "money")
_p(r'[\$\£\€\¥]{2,}', "£££", "money")
_p(r'\b[0-9\.,]+%( off)?\b', "50% off", "money")
_p(r'\ba few bob\b', "A few bob", "money")
_p(r'\baccept cash cards\b', "Accept cash cards", "money")
_p(r'\baccept credit cards\b', "Accept credit cards", "money")
_p(r'\baffordable\b', "Affordable", "money")
_p(r'\baffordable deal\b', "Affordable deal", "money")
_p(r'\bavoid bankruptcy\b', "Avoid bankruptcy", "money")
_p(r'\bbad credit\b', "Bad credit", "money")
_p(r'\bbank\b', "Bank", "money")
_p(r'\bbankruptcy\b', "Bankruptcy", "money")
_p(r'\bbargain\b', "Bargain", "money")
_p(r'\bbilling\b', "Billing", "money")
_p(r'\bbilling address\b', "Billing address", "money")
_p(r'\bbillion\b', "Billion", "money")
_p(r'\bbillion dollars\b', "Billion dollars", "money")
_p(r'\bbillionaire\b', "Billionaire", "money")
_p(r'\bcard accepted\b', "Card accepted", "money")
_p(r'\bcards accepted\b', "Cards accepted", "money")
_p(r'\bcash\b', "Cash", "money")
_p(r'\bcash bonus\b', "Cash bonus", "money")
_p(r'\bcash out\b', "Cash out", "money")
_p(r'\bcash-out\b', "Cash-out", "money")
_p(r'\bcashcashcash\b', "Cashcashcash", "money")
_p(r'\bcasino\b', "Casino", "money")
_p(r'\bcents on the dollar\b', "Cents on the dollar", "money")
_p(r'\bcheck\b', "Check", "money")
_p(r'\bcheck or money order\b', "Check or money order", "money")
_p(r'\bclaim your discount\b', "Claim your discount", "money")
_p(r'\bcost\b', "Cost", "money")
_p(r'\bcosts\b', "Costs", "money")
_p(r'\bcredit\b', "Credit", "money")
_p(r'\bcredit bureaus\b', "Credit bureaus", "money")
_p(r'\bcredit card\b', "Credit card", "money")
_p(r'\bcredit card offers\b', "Credit card offers", "money")
_p(r'\bcredit or debit\b', "Credit or Debit", "money")
_p(r'\bdeal\b', "Deal", "money")
_p(r'\bdebt\b', "Debt", "money")
_p(r'\bdiscount\b', "Discount", "money")
_p(r'\bdollars\b', "Dollars", "money")
_p(r'\bdouble your\b', "Double your", "money")
_p(r'\bdouble your wealth\b', "Double your wealth", "money")
_p(r'\bearn\b', "Earn", "money")
_p(r'\bearn [\$\£\€\¥]+\b', "Earn $", "money")
_p(r'\bearn cash\b', "Earn cash", "money")
_p(r'\bearn extra income\b', "Earn extra income", "money")
_p(r'\bearn from home\b', "Earn from home", "money")
_p(r'\bearn monthly\b', "Earn monthly", "money")
_p(r'\bearn per month\b', "Earn per month", "money")
_p(r'\bearn per week\b', "Earn per week", "money")
_p(r'\bearn your degree\b', "Earn your degree", "money")
_p(r'\beasy income\b', "Easy income", "money")
_p(r'\beasy terms\b', "Easy terms", "money")
_p(r'\bf r e e\b', "F r e e", "money")
_p(r'\bfor free\b', "For free", "money")
_p(r'\bfor just [\$\£\€\¥]+\b', "For just $", "money")
_p(r'\bfor just [\$\£\€\¥]+[0-9]+\b', "For just $ (amount)", "money")
_p(r'\bfor just [\$\£\€\¥]+xxx\b', "For just $xxx", "money")
_p(r'\bget money\b', "Get Money", "money")
_p(r'\bget your money\b', "Get your money", "money")
_p(r'\bhidden assets\b', "Hidden assets", "money")
_p(r'\bhuge discount\b', "Huge discount", "money")
_p(r'\bincome\b', "Income", "money")
_p(r'\bincome from home\b', "Income from home", "money")
_p(r'\bincrease revenue\b', "Increase revenue", "money")
_p(r'\bincrease (sales|traffic)\b', "Increase sales/traffic", "money")
_p(r'\bincrease your chances\b', "Increase your chances", "money")
_p(r'\binitial investment\b', "Initial investment", "money")
_p(r'\binstant earnings\b', "Instant earnings", "money")
_p(r'\binstant income\b', "Instant income", "money")
_p(r'\binsurance\b', "Insurance", "money")
_p(r'\binvestment\b', "Investment", "money")
_p(r'\binvestment advice\b', "Investment advice", "money")
_p(r'\blifetime\b', "Lifetime", "money")
_p(r'\bloans\b', "Loans", "money")
_p(r'\bmake [\$\£\€\¥]+\b', "Make $", "money")
_p(r'\bmoney\b', "Money", "money")
_p(r'\bmoney making\b', "Money making", "money")
_p(r'\bmoney-back guarantee\b', "Money-back guarantee", "money")
_p(r'\bmoney-making\b', "Money-making", "money")
_p(r'\bmonthly payment\b', "Monthly payment", "money")
_p(r'\bmortgage\b', "Mortgage", "money")
_p(r'\bmortgage rates\b', "Mortgage rates", "money")
_p(r'\boffer\b', "Offer", "money")
_p(r'\bone hundred percent free\b', "One hundred percent free", "money")
_p(r'\bonly [\$\£\€\¥]+\b', "Only $", "money")
_p(r'\bprice\b', "Price", "money")
_p(r'\bprice protection\b', "Price protection", "money")
_p(r'\bprices\b', "Prices", "money")
_p(r'\bprofits\b', "Profits", "money")
_p(r'\bquote\b', "Quote", "money")
_p(r'\brates\b', "Rates", "money")
_p(r'\brefinance\b', "Refinance", "money")
_p(r'\bsave [\$\£\€\¥]+\b', "Save $", "money")
_p(r'\bserious cash\b', "Serious cash", "money")
_p(r'\bsubject to credit\b', "Subject to credit", "money")
_p(r'\bUS Dollars\b', "US Dollars", "money")
_p(r'\bwhy pay more\?\b', "Why pay more?", "money")
_p(r'\byour income\b', "Your income", "money")

# ── Unnatural (75 patterns) ─────────────────────────────────────────
_p(r'\bacceptance\b', "Acceptance", "unnatural")
_p(r'\baccordingly\b', "Accordingly", "unnatural")
_p(r'\baccount-based marketing \(abm\)\b', "Account-based marketing (ABM)", "unnatural")
_p(r'\baccounts\b', "Accounts", "unnatural")
_p(r'\baddresses\b', "Addresses", "unnatural")
_p(r'\baddresses on cd\b', "Addresses on CD", "unnatural")
_p(r'\bbeverage\b', "Beverage", "unnatural")
_p(r'\bconfidentiality on all orders\b', "Confidentiality on all orders", "unnatural")
_p(r'\bconfidentially on all orders\b', "Confidentially on all orders", "unnatural")
_p(r'\bcontent marketing\b', "Content marketing", "unnatural")
_p(r'\bdear(est)? (.+@.+)\b', "Dear [email address]", "unnatural")
_p(r'\bdear(est)? (email|friend|somebody)\b', "Dear [email/friend/somebody]", "unnatural")
_p(r'\bdear \[first name\]\b', "Dear [first name]", "unnatural")
_p(r'\bdear \[wrong name\]\b', "Dear [wrong name]", "unnatural")
_p(r'\bdigital marketing\b', "Digital marketing", "unnatural")
_p(r'\bdormant\b', "Dormant", "unnatural")
_p(r'\bemail extractor\b', "Email extractor", "unnatural")
_p(r'\bemail harvest\b', "Email harvest", "unnatural")
_p(r'\bemail marketing\b', "Email marketing", "unnatural")
_p(r'\bextract email\b', "Extract email", "unnatural")
_p(r'\bform\b', "Form", "unnatural")
_p(r'\bfreedom\b', "Freedom", "unnatural")
_p(r'\bfriend\b', "Friend", "unnatural")
_p(r'\bhere\b', "Here", "unnatural")
_p(r'\bhidden\b', "Hidden", "unnatural")
_p(r'\bhome\b', "Home", "unnatural")
_p(r'\bhome based\b', "Home based", "unnatural")
_p(r'\bhome employment\b', "Home employment", "unnatural")
_p(r'\bhome-based\b', "Home-based", "unnatural")
_p(r'\bhome-based business\b', "Home-based business", "unnatural")
_p(r'\bhomebased business\b', "Homebased business", "unnatural")
_p(r'\bif you no longer wish to receive\b', "If you no longer wish to receive", "unnatural")
_p(r'\bimportant information regarding\b', "Important information regarding", "unnatural")
_p(r'\bin accordance with laws\b', "In accordance with laws", "unnatural")
_p(r'\bincrease your sales\b', "Increase your sales", "unnatural")
_p(r'\binternet market\b', "Internet market", "unnatural")
_p(r'\bleave\b', "Leave", "unnatural")
_p(r'\blose\b', "Lose", "unnatural")
_p(r'\bmaintained\b', "Maintained", "unnatural")
_p(r'\bmarketing\b', "Marketing", "unnatural")
_p(r'\bmarketing solution\b', "Marketing solution", "unnatural")
_p(r'\bmarketing solutions\b', "Marketing solutions", "unnatural")
_p(r'\bmedium\b', "Medium", "unnatural")
_p(r'\bmessage contains\b', "Message contains", "unnatural")
_p(r'\bmulti level marketing\b', "Multi level marketing", "unnatural")
_p(r'\bnever\b', "Never", "unnatural")
_p(r'\bone time mailing\b', "One time mailing", "unnatural")
_p(r'\bonline marketing\b', "Online marketing", "unnatural")
_p(r'\bonline pharmacy\b', "Online pharmacy", "unnatural")
_p(r'\bopt in\b', "Opt in", "unnatural")
_p(r'\bper day\b', "Per day", "unnatural")
_p(r'\bper week\b', "Per week", "unnatural")
_p(r'\bpre-approved\b', "Pre-approved", "unnatural")
_p(r'\bproblem\b', "Problem", "unnatural")
_p(r'\bremoval\b', "Removal", "unnatural")
_p(r'\bremove\b', "Remove", "unnatural")
_p(r'\breserves the right\b', "Reserves the right", "unnatural")
_p(r'\breverses\b', "Reverses", "unnatural")
_p(r'\bsample\b', "Sample", "unnatural")
_p(r'\bsatisfaction\b', "Satisfaction", "unnatural")
_p(r'\bscore\b', "Score", "unnatural")
_p(r'\bsearch engine\b', "Search engine", "unnatural")
_p(r'\bsearch engine listings\b', "Search engine listings", "unnatural")
_p(r'\bsearch engines\b', "Search engines", "unnatural")
_p(r'\bsent in compliance\b', "Sent in compliance", "unnatural")
_p(r'\bsolution\b', "Solution", "unnatural")
_p(r'\bstop\b', "Stop", "unnatural")
_p(r'\bsuccess\b', "Success", "unnatural")
_p(r'\bteen\b', "Teen", "unnatural")
_p(r'\bterms and conditions\b', "Terms and conditions", "unnatural")
_p(r'\bwarranty\b', "Warranty", "unnatural")
_p(r'\bweb traffic\b', "Web traffic", "unnatural")
_p(r'\bwife\b', "Wife", "unnatural")
_p(r'\bwork at home\b', "Work at home", "unnatural")
_p(r'\bwork from home\b', "Work from home", "unnatural")


# ─── Scoring engine ─────────────────────────────────────────────────

CATEGORY_ICONS = {
    "urgency": "🚨",
    "shady": "🔞",
    "overpromise": "🤩",
    "money": "💰",
    "unnatural": "💬",
}


def check_spam(text: str) -> dict:
    """
    Run all spam patterns against text. Returns a dict with:
      - score: int
      - rating: "Great" | "Okay" | "Poor"
      - total_hits: int
      - word_count: int
      - categories: {category: [{"keyword": str, "match": str}]}
      - flagged_words: [{"keyword": str, "category": str, "match": str}]
    """
    words = text.split()
    word_count = len(words)

    categories: dict[str, list[dict]] = {}
    flagged: list[dict] = []
    seen: set[tuple[str, str]] = set()  # (keyword, category) dedup

    for pattern, keyword, category in SPAM_PATTERNS:
        for match in pattern.finditer(text):
            key = (keyword, category)
            if key not in seen:
                seen.add(key)
                entry = {"keyword": keyword, "category": category, "match": match.group()}
                flagged.append(entry)
                categories.setdefault(category, []).append(entry)

    total_hits = len(flagged)

    # Scoring — exact Mailmeteor algorithm
    score = total_hits
    if "money" in categories or "shady" in categories:
        score += 20
    if "urgency" in categories or "overpromise" in categories:
        score += 10

    if score > 20:
        rating = "Poor"
    elif score > 5:
        rating = "Okay"
    else:
        rating = "Great"

    return {
        "score": score,
        "rating": rating,
        "total_hits": total_hits,
        "word_count": word_count,
        "categories": categories,
        "flagged_words": flagged,
    }


# ─── Output formatters ──────────────────────────────────────────────

def format_human(result: dict, text: str) -> str:
    """Format results for terminal display."""
    lines = []

    # Score header
    rating = result["rating"]
    color = {"Great": "\033[32m", "Okay": "\033[33m", "Poor": "\033[31m"}
    reset = "\033[0m"
    lines.append(f"\n{'─' * 50}")
    lines.append(f"  Score: {color.get(rating, '')}{rating}{reset}  ({result['total_hits']} spam triggers found)")
    lines.append(f"  Words: {result['word_count']}")
    lines.append(f"{'─' * 50}")

    if not result["flagged_words"]:
        lines.append("  ✅ No spam trigger words detected!")
        return "\n".join(lines)

    # Category breakdown
    for cat in ["urgency", "shady", "overpromise", "money", "unnatural"]:
        if cat not in result["categories"]:
            continue
        items = result["categories"][cat]
        icon = CATEGORY_ICONS[cat]
        lines.append(f"\n  {icon} {cat.title()} ({len(items)})")
        for item in sorted(items, key=lambda x: x["keyword"].lower()):
            lines.append(f"     • {item['keyword']}")

    lines.append("")
    return "\n".join(lines)


def format_json(result: dict) -> str:
    """Format results as JSON."""
    output = {
        "score": result["score"],
        "rating": result["rating"],
        "total_hits": result["total_hits"],
        "word_count": result["word_count"],
        "categories": {
            cat: [item["keyword"] for item in items]
            for cat, items in result["categories"].items()
        },
    }
    return json.dumps(output, indent=2)


# ─── CLI ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Check email copy for spam trigger words (772 patterns, 5 categories)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  echo "Click here for a free offer!" | python spam_checker.py
  python spam_checker.py --text "Act now, limited time only!"
  python spam_checker.py --file email.txt --json
  python spam_checker.py --dir campaigns/""",
    )
    source = parser.add_mutually_exclusive_group()
    source.add_argument("--text", "-t", help="Email text to check")
    source.add_argument("--file", "-f", help="File containing email text")
    source.add_argument("--dir", "-d", help="Directory of .txt/.md files to batch check")
    parser.add_argument("--json", "-j", action="store_true", help="Output as JSON")
    parser.add_argument("--quiet", "-q", action="store_true", help="Only show flagged words, no header")

    args = parser.parse_args()

    # Determine input
    if args.dir:
        # Batch mode
        p = Path(args.dir)
        files = sorted(p.glob("*.txt")) + sorted(p.glob("*.md"))
        if not files:
            print(f"No .txt or .md files found in {args.dir}")
            sys.exit(1)

        results = []
        for f in files:
            text = f.read_text(encoding="utf-8", errors="replace")
            result = check_spam(text)
            result["file"] = str(f)
            results.append(result)

        if args.json:
            batch_output = []
            for r in results:
                batch_output.append({
                    "file": r["file"],
                    "score": r["score"],
                    "rating": r["rating"],
                    "total_hits": r["total_hits"],
                    "categories": {
                        cat: [item["keyword"] for item in items]
                        for cat, items in r["categories"].items()
                    },
                })
            print(json.dumps(batch_output, indent=2))
        else:
            # Summary table
            print(f"\n{'File':<40} {'Rating':<8} {'Hits':<6} {'Categories'}")
            print("─" * 80)
            for r in results:
                cats = ", ".join(f"{cat}({len(items)})" for cat, items in r["categories"].items())
                color = {"Great": "\033[32m", "Okay": "\033[33m", "Poor": "\033[31m"}
                reset = "\033[0m"
                fname = Path(r["file"]).name
                if len(fname) > 38:
                    fname = fname[:35] + "..."
                print(f"  {fname:<38} {color.get(r['rating'], '')}{r['rating']:<8}{reset} {r['total_hits']:<6} {cats}")
            print()
        sys.exit(0)

    if args.text:
        text = args.text
    elif args.file:
        text = Path(args.file).read_text(encoding="utf-8", errors="replace")
    elif not sys.stdin.isatty():
        text = sys.stdin.read()
    else:
        parser.print_help()
        sys.exit(1)

    result = check_spam(text)

    if args.json:
        print(format_json(result))
    elif args.quiet:
        for item in result["flagged_words"]:
            print(f"{item['category']}: {item['keyword']}")
    else:
        print(format_human(result, text))


if __name__ == "__main__":
    main()
